name: Build & release liascript-preview-web plugin
on:
  push:
    tags:    # Sequence of patterns matched against refs/tags
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  release-project:
    name: Release liascript-preview-web plugin
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

  build-project:
    name: Build liascript-preview-web plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: npm install
      - name: Install vsce
        run: npm install -g vsce
      - name: Build plugin
        run: vsce package
      - name: Upload plugin
        uses: actions/upload-artifact@v2
        with:
          path: '*.vsix'
